<a href="https://colab.research.google.com/github/jaewoo-cho/jaewoo/blob/master/23_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy
**Num**erical **Py**thon

<img src="https://numpy.org/images/logo.svg" width="100" height="100"/>

[공식] (https://numpy.org/)



In [ ]:
# numpy : 수치적 연산을 위해 최적화된 모듈
#  파이썬을 활용한 데이터 분석에서  가장 기본!
#  이 자체로도 많이 쓰이거니와, 앞으로 배울 pandas, 머신러닝 등 수많은 분야에서 기본적으로 사용하는 모듈
#  파이썬 개발자라면 꼭 익힐 필요 있다

# 수학수치 연산  (numerical python) / 합, 평균, 행렬연산 등..
# 추가적으로 scipy, statsmodel  같은 것들도 numpy 기반으로 구현됨.
# 상황에 따라, pandas 안써도 numpy 만으로도 가능.

# 기본 타입 : ndarray  (n-dimensional array) 다차원 배열 표현

# 파이썬에 list 가 있는데 굳이? 왜?  -

# numpy 를 사용하는 이유
# 1. 성능 : 성능적으로 훨~씬 빠름.
# 2. 메모리 : 훨씩 적은 메모리사용
# 3. 제공함수풍부 : 선형대수, 통계관련 여러 수치함수 제공
# 4. 수많은 모듈에서 numpy 함수명 과 기능을 그대로 사용.

In [ ]:
import numpy as np

![aaa](https://statkclee.github.io/deep-learning/fig/tensor.jpg)

**Scalar** : 0차원 array (단일값)

**Vector** : 1차원 array

**Matrix** : 2차원 array

**Tensor** : 3차원(이상) array


# 1차원 array (벡터) 생성

In [ ]:
# np,array(iterable)

x = np.array([1,2,3])
y = np.array([2,4,15])

In [ ]:
print(y)

[ 2  4 15]


In [ ]:
y

array([ 2,  4, 15])

In [ ]:
# scalar (0차원)
np.array(10)

array(10)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
[1, 2, 3.14, '김', True] # 리스트는 원소타입이 제각각 가능

[1, 2, 3.14, '김', True]

In [ ]:
# 그러나!  array 는 모든 원소는 '한가지 타입' 이어야 함!

# shape, size, ndim, dtype, len()

In [ ]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

## shape
numpy에서는 해당 array의 크기를 알 수 있다.<br>
shape 을 확인함으로써 몇개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인할 수 있다.<br>
위에서 arr1.shape의 결과는 (5,) 으로써, 1차원의 데이터이며 총 5라는 크기를 갖고 있음을 알 수 있다.
arr4.shape의 결과는 (4,3) 으로써, 2차원의 데이터이며 4 * 3 크기를 갖고 있는 array 이다.



In [ ]:
arr.shape

(5,)

In [ ]:
## ndim 차원수

In [ ]:
arr.ndim

# .ndim 과 len(arr.shape) 는 같다

1

## size: 데이터의 개수

In [ ]:
arr.size

5

# len(array)
array 는 literable 하다

In [ ]:
len(arr)

5

# dtype: data type

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr2 = np.array([10, 3.14, 2, 0.12])
arr2

array([10.  ,  3.14,  2.  ,  0.12])

In [ ]:
arr2.dtype

dtype('float64')

In [ ]:
# numpy에서 사용되는 자료형은 아래와 같다. (자료형 뒤에 붙는 숫자는 몇 비트 크기인지를 의미한다.)

# 부호가 있는 정수 int(8, 16, 32, 64)
# 부호가 없는 정수 uint(8 ,16, 32, 64)
# 실수 float(16, 32, 64, 128)
# 복소수 complex(64, 128, 256)
# 불리언 bool
# 문자열 string_
# 파이썬 오프젝트 object
# 유니코드 unicode_

# 2차원 array 생성

In [ ]:
x = np.array([1,2,3,4])
y = np.array([[2,3,4],[1,2,4]])

In [ ]:
y

array([[2, 3, 4],
       [1, 2, 4]])

In [ ]:
x.shape

(4,)

In [ ]:
y.shape

(2, 3)

In [ ]:
y.ndim

2

In [ ]:
x.ndim

1

In [ ]:
len(x)

4

In [ ]:
len(y)

2

In [ ]:
x.size

4

In [ ]:
y.size

6

# 3차원 array

In [ ]:
# (2,3,4)

z = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
z

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
z.shape

(2, 3, 4)

In [ ]:
z.size

24

# 같은 값이라도 '차원' 이 다를 수 있다
'차원변환' 중요하다!

In [ ]:
np.array(10) #0차원

array(10)

In [ ]:
np.array([10]) #1차원

array([10])

In [ ]:
np.array([[10]]) #2차원

array([[10]])

In [ ]:
np.array([[[10]]]) #3차원

array([[[10]]])

# np.arange()

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
np.arange(1, 10, dtype=np.int16)

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

# astype(타입)
타입변환한 array 를 리턴 (원본 변화 없슴!)


In [ ]:
d = np.arange(3, 10)
d  #dtype = int64

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
d.astype(np.float32)

array([3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [ ]:
d

array([3, 4, 5, 6, 7, 8, 9])

# reshape()
 - ndarray의 형태, 차원을 바꾸기 위해 사용
 - 머신러닝, 데이터 프로세싱에서 매우 자주 사용됨. (차원변환)

In [ ]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(12).reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
np.arange(12).reshape(3, 2, 2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

# np.ones, np.zeros

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones(6).reshape(2, 3)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((2,3), dtype=np.int16)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [ ]:
np.zeros((3,2,5), dtype=np.uint8)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=uint8)

In [ ]:
# 단위 행렬
np.eye(5) # (5, 5)단위 행렬

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# np.random 서브모듈

In [ ]:
# rand: 0부터 1사이의 균일 분포 [0, 1)  uniform distribution
# randn: 가우시안 표준 정규 분포
# randint: 균일 분포의 정수 난수

In [ ]:
np.random.rand(10)

array([0.11041767, 0.61628789, 0.9359328 , 0.61811622, 0.70163503,
       0.83838652, 0.00221579, 0.22022948, 0.13428675, 0.0404863 ])

In [ ]:
np.random.rand(2,3)

array([[0.7200284 , 0.2473767 , 0.86433512],
       [0.20568534, 0.65096986, 0.87930281]])

![](https://thebook.io/img/080263/218.jpg)


In [ ]:
np.random.randn(5)

array([-1.94897711, -0.15235786,  0.09882428,  0.53622632, -0.3133693 ])

In [ ]:
np.random.randint(5) # 0-4 사이에 정수 난수

4

In [ ]:
np.random.randint(1,10) # 1부터 9까지 난수

5

In [ ]:
np.random.randint(1, 100, (3,5,2))

array([[[ 1, 73],
        [30, 71],
        [25, 41],
        [16, 87],
        [48, 47]],

       [[ 1, 22],
        [35, 64],
        [ 6, 48],
        [10, 63],
        [ 5, 71]],

       [[ 9, 88],
        [89, 40],
        [99, 24],
        [45, 32],
        [36,  6]]])

In [ ]:
np.random.rand(4)

array([0.82077157, 0.27650703, 0.5746884 , 0.21226799])

In [ ]:
np.random.seed(0)
np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

# np.unique()




In [ ]:
np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

# 인덱싱 index
 - 파이썬 리스트와 동일한 개념으로 사용
 - ,를 사용하여 각 차원의 인덱스에 접근 가능
 - 인덱싱 할때마다 차원감소

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[0]

0

In [ ]:
x[-1]

9

In [ ]:
x[9]

9

In [ ]:
x[3]=100
x

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [ ]:
x = np.arange(10).reshape(2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
x[0]

array([0, 1, 2, 3, 4])

In [ ]:
x[0][2]

2

In [ ]:
x[0, 2] # <- 콤마로 인덱싱 가능!  numpy 에선 후자의 방법을 추천!

2

In [ ]:
x[1, 4]

9

In [ ]:
x[1, 4], x[1, -1]

(9, 9)

## Advanced Indexing
- Integer array indexing

In [ ]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
x[[0]]

array([[0, 1, 2, 3, 4]])

In [ ]:
x[0]

array([0, 1, 2, 3, 4])

In [ ]:
x[[1, 0]]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

# 슬라이싱
 - 리스트, 문자열 slicing과 동일한 개념으로 사용
 - ,를 사용하여 각 차원 별로 슬라이싱 가능
 - 슬라이싱은 차원 변화 없다


In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [ ]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[::2]

array([0, 2, 4, 6, 8])

In [ ]:
x[1::3]

array([1, 4, 7])

In [ ]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
y = [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9],
     [10, 11, 12, 13, 14]]
y

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [ ]:
y[0:1]

[[0, 1, 2, 3, 4]]

In [ ]:
y[1:3]

[[5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [ ]:
y[:2]

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]

In [ ]:
y[:2][1:4]

[[5, 6, 7, 8, 9]]

In [ ]:
# list 는 차원별 슬라이싱 안됨

In [ ]:
x = np.arange(15).reshape(3, 5)
x


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
x[:2][1:4]

array([[5, 6, 7, 8, 9]])

In [ ]:
x[:2, 1:4] # array 는 차원별 슬라이싱 됨

array([[1, 2, 3],
       [6, 7, 8]])

---
# shape (차원) 변경하기
**차원변환**은 데이터분석 과 인공지능에서 매우 빈번하게 발생되는 작업이니만큼 자유자재로 변환할수 있어야 하고, 머리속으로 내가 변환하는 데이터의 구조가 그려지도록 익숙해져야 합니다

사용 예) 이미지 데이터 벡터화 - 이미지는 기본적으로 2차원 혹은 3차원(RGB)이나 트레이닝을 위해 1차원으로 변경하여 사용 됨


## ravel(), np.ravel()
  - [ˈrævl]
  - 다차원배열을 1차원으로 변경 (흔히 **'펼친다'**라고 말함)
  - 'order' 파라미터
    - 'C' - row 우선 변경 ,   C style
    - 'F - column 우선 변경,   Fortran style
  - ravel() 은 np 안에 일반 함수로도 있고, 혹은 ndarray 의 멤버함수로서도 존재


In [ ]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.ravel(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.ravel(x, order='C') # row(행) 방향 (axis 0부터 펼쳐짐)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.ravel(x, order='F') # column 방향으로 (axis -1 부터 펼쳐짐)

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

## flatten()
 - 다차원 배열을 1차원으로 변경
 - ravel과의 차이점:
     - copy를 생성하여 변경함(즉 원본 데이터가 아닌 복사본을 반환)
     - ndarray 의 멤버함수로만 제공됨
 - 'order' 파라미터
   - 'C' - row 우선 변경
   - 'F - column 우선 변경

In [ ]:
y = np.arange(15).reshape(3, 5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
temp = x.ravel()
temp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
temp[0] = 100
temp

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [ ]:
x

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [ ]:
temp2 = y.flatten() # 데이터의 복사본을 생성함
temp2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
temp2[0]=100
temp2

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [ ]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## reshape 함수
 - array의 shape을 다른 차원으로 변경
 - 주의할점은 reshape한 후의 결과의 전체 원소 개수와 이전 개수가 같아야 가능
 - 사용 예) 이미지 데이터 벡터화 - 이미지는 기본적으로 2차원 혹은 3차원(RGB)이나 트레이닝을 위해 1차원으로 변경하여 사용 됨
 - **-1** 값을 주어 나머지 차원을 유추하게 할수 있다


In [ ]:
x2 = np.arange(36)
x2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [ ]:
x2.reshape(6, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
x2.reshape(6, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
x2. reshape(6, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]]])

## 차원 확장 / 제거

- 차원 확장/제거 하는 동작도 머신러닝에서 많이 사용된다.
- **reshape()** 로 차원 변환(확장/제거) 자유롭게 가능

## 차원 확장 : np.expand_dims()
- axis로 지정된 '차원을 추가'한다.


## 차원 자동 제거 : squeeze, np.squeeze()

- 차원 중 사이즈가 1인 것을 찾아 스칼라값으로 바꿔 해당 '차원을 제거'한다.


In [ ]:
x3 = np.arange(6)
x3

array([0, 1, 2, 3, 4, 5])

In [ ]:
x3.shape

(6,)

In [ ]:
x3 = x3.reshape(6, 1) # 차원 확장
x3

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
x3.shape

(6, 1)

In [ ]:
x3 = x3.reshape(6, 1, 1)
x3

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [ ]:
x3 = x3.reshape(6, )
x3

array([0, 1, 2, 3, 4, 5])

In [ ]:
x3 = x3.reshape(6, 1)
x3

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
x3 = x3.reshape(1, 1, 1, 6)
x3

array([[[[0, 1, 2, 3, 4, 5]]]])

In [ ]:
x3.squeeze() # 차원크기가 1인 차원을 제거

array([0, 1, 2, 3, 4, 5])

In [ ]:
x4 = np.arange(4).reshape((2, 1, 2))
x4

array([[[0, 1]],

       [[2, 3]]])

In [ ]:
x4.squeeze()

array([[0, 1],
       [2, 3]])

In [ ]:
x5 = np.arange(3) #(3,)
x5

array([0, 1, 2])

In [ ]:
y5 = np.expand_dims(x5, axis=0) #0번째 차원축(axis)에 새로운 차원 추가(삽입)
y5

array([[0, 1, 2]])

In [ ]:
y5.shape

(1, 3)

In [ ]:
x6 = np.arange(4).reshape(2, 2)
x6

array([[0, 1],
       [2, 3]])

In [ ]:
# (2, 2) -> (2, 2, 1)

y7 = np.expand_dims(x6, axis=2)
y7

array([[[0],
        [1]],

       [[2],
        [3]]])

In [ ]:
a = np.array([2, 0, 1, 8])
a

array([2, 0, 1, 8])

In [ ]:
# (4,) ->(1.4)

a1 = a[np.newaxis,:]
print(a1.shape)
a1

(1, 4)


array([[2, 0, 1, 8]])

In [ ]:
# ↑ 1차원 벡터를 'row vector' 로 변환한다 라고도 함.

In [ ]:
a2 = a[:, np.newaxis] # (4,) -> (4,1)
print(a2.shape)
a2

(4, 1)


array([[2],
       [0],
       [1],
       [8]])

In [ ]:
# ↑ 1차원 벡터를 'column vector' 로 변환한다 라고도 함.

# transpose, T,  swapaxes
전치행렬 (transpose matrix) , 차원 축 바꾸기

![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbtmNz3%2FbtqDk6Xy5nh%2FD7U80E2R3fnahK00cijoY1%2Fimg.png)


In [ ]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
np.transpose(a) #(3, 5) -> (5,3)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
a.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
np.swapaxes(a, 0, 1) # axis 0과 axis 1을 바꾸기

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# 기본연산, 기본함수

In [ ]:
x = np.arange(15).reshape(3, 5)
y = np.arange(0, 150, 10).reshape(3, 5)
y2 = np.random.rand(15).reshape(3, 5)
y3 = np.arange(15).reshape(5, 3)

In [ ]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
y

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140]])

In [ ]:
y2

array([[0.4236548 , 0.64589411, 0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492, 0.56804456, 0.92559664],
       [0.07103606, 0.0871293 , 0.0202184 , 0.83261985, 0.77815675]])

In [ ]:
y3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# array 간 연산

In [ ]:
# 리스트의 경우
a = [10, 20, 30, 40]
b = 2
c = [100, 200, 300, 400]


In [ ]:
a * 2

[10, 20, 30, 40, 10, 20, 30, 40]

In [ ]:
a+c

[10, 20, 30, 40, 100, 200, 300, 400]

In [ ]:
# array 연산은 리스트와 다르다!
# 기본적으로 '원소' 끼리 연산


In [ ]:
x + y

array([[  0,  11,  22,  33,  44],
       [ 55,  66,  77,  88,  99],
       [110, 121, 132, 143, 154]])

In [ ]:
# 단일값만 갖고 있는 객체와는 shape 관계없이, scalar 연산 수행


In [ ]:
x + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
x + [10]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
x +[[10]]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
x + np.array(10)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# axis (차원축)

In [ ]:
"""
numpy 의 많은 함수들은 axis=  파라미터를 갖고 있습니다.
axis (축) 은 각 '차원' 을 의미합니다.
1차원 array 라면  각 차원에 대한 axis 값은 0  <- 1개 입니다.
2차원 array 라면  각 차원에 대한 axis 값은 0, 1  <- 2개 입니다.
3차원 array 라면  각 차원에 대한 axis 값은 0, 1, 2  <- 3개 입니다.

axis= 값을 명시하면 그 함수의 연산 은 해당 axis(축) 에 '따라서' 연산을 수행함

과연 '따라서' 의 의미가 무엇인지 실습을 통해 이해해봅시다
"""
None

In [ ]:
x1 = np.arange(15)
x1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.sum(x1)

105

In [ ]:
x2 = x1.reshape(3, 5)

In [ ]:
x2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
x2.shape
# (행, 열)
# (axis 0, axis 1)

(3, 5)

In [ ]:
np.sum(x2) #axis = 0

105

In [ ]:
np.sum(x2, axis=1)

array([10, 35, 60])

In [ ]:
np.sum(x2, axis=0) # (3,5) -> (5,)

# 15 = 0 + 5 + 10
# [0,0] + [1,0] + [2,0]

array([15, 18, 21, 24, 27])

In [ ]:
y = np.random.rand(15).reshape(3, 5)
y

array([[0.87001215, 0.97861834, 0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329, 0.94466892, 0.52184832],
       [0.41466194, 0.26455561, 0.77423369, 0.45615033, 0.56843395]])

In [ ]:
np.max(y)

0.978618342232764

In [ ]:
np.argmax(y) # 최댓값의 index

1

In [ ]:
np.max(y, axis=0)

array([0.87001215, 0.97861834, 0.79915856, 0.94466892, 0.78052918])

In [ ]:
np.argmax(y, axis=0)

array([0, 0, 0, 1, 0])

# Broadcasting
#### 브로드캐스팅
  - (기본적으로는) Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - **다른 Shape을 갖는 array 간 연산** 의 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
   
   
![](https://numpy.org/doc/stable/_images/broadcasting_1.png)


In [ ]:
x = np.arange(15).reshape(3, 5)

In [ ]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
y = np.random.rand(15).reshape(3,5)

In [ ]:
y

array([[0.0187898 , 0.6176355 , 0.61209572, 0.616934  , 0.94374808],
       [0.6818203 , 0.3595079 , 0.43703195, 0.6976312 , 0.06022547],
       [0.66676672, 0.67063787, 0.21038256, 0.1289263 , 0.31542835]])

In [ ]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)


In [ ]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
b

array([100, 101, 102])

In [ ]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

### 브로드캐스팅 Rule
 - [Rule 공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 **①Shape이 같거나**, **②차원 중 값이 1이 존재**하면 broadcasting 가능
 - 결과 차원은 둘중 큰 size 의 차원으로 **확장** 된다



![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg


In [ ]:
''' 브로드캐스팅 가용한 경우
    A     : 256 x 256 x 3
    B     :             3
    Result: 256 x 256 x 3   <-- 결과 차원은 둘중 큰 size의 차원으로 확장

    A     : 8 x 1 x 6 x 1
    B     :     7 x 1 x 5
    Result: 8 x 7 x 6 x 5
'''


''' 브로드캐스팅 불가능한 경우
    A     : 3
    B     : 4

    A     :     2 x 1
    B     : 8 x 4 x 3
'''
None


In [ ]:
c = np.arange(1000,1004)

In [ ]:
print(a.shape)
print(c.shape)

(4, 3)
(4,)


In [ ]:
a = np.full(4, 100)
a #(4,)

array([100, 100, 100, 100])

In [ ]:
b = np.arange(1, 9).reshape(2,4)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# a (4,)
# b (2,4)
# a+b = (2,4)
a+b

array([[101, 102, 103, 104],
       [105, 106, 107, 108]])

In [ ]:
b = np.array([[1],[2]])
b #(2,1)

array([[1],
       [2]])

In [ ]:
a + b

array([[101, 101, 101, 101],
       [102, 102, 102, 102]])

In [ ]:
arr21 = np.arange(10, 70, 10).reshape(2, 3)
arr21

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
arr23 = np.array([1,2])
arr23 #(2,)

array([1, 2])

In [ ]:
# 도전!  위 두개의 array 를 더하여
# 과연 아래의 결과를 만들수 있을까?
""" 원하는 결과
array([[11, 22, 31],
       [42, 51, 62]])
"""
None

array([[11, 21, 31],
       [42, 52, 62]])

In [ ]:
(arr21.reshape(3,2) + arr23).reshape(2,3)

array([[11, 22, 31],
       [42, 51, 62]])

In [ ]:
arr21

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
arr21.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
arr23

array([1, 2])

# Boolean Indexing

In [ ]:
# 'Boolean indexing ' !
# array 인덱싱 시, bool 리스트(aka. mask)를 전달하여 True인 경우만 필터링

# for 사용하지 않고도 array 에서 '조건'에 맞는 데이터만 추출 하는 기능

In [ ]:
x = np.random.randint(1, 100, size=10)

In [ ]:
x

array([54, 13, 43, 85, 76, 69,  7, 69, 48,  4])

In [ ]:
x % 2

array([0, 1, 1, 1, 0, 1, 1, 1, 0, 0])

In [ ]:
even_mask = x % 2 == 0
even_mask

array([ True, False, False, False,  True, False, False, False,  True,
        True])

In [ ]:
# 위와 같이 bool 값으로 이루어진 array 를 Mask 라고도 한다
# 위 결과, mask 를 변수에 담아 보겠습니다

# boolean mask 로 인덱싱!


In [ ]:
x[even_mask]

array([54, 76, 48,  4])

In [ ]:
# list 나 tuple 같은 iterable 도 bool mask 로 사용 가능.

x[[ True,  True,  True,  True, False, False, False, False, False, True]]


array([54, 13, 43, 85,  4])

## 다중조건 사용하기
 - 파이썬 논리 연산자인 and, or, not 키워드는 사용 불가
 - & ← AND
 - | ← OR


In [ ]:
x[(x%2==0) & (x<30)]

array([4])

# astype() 으로 변환

In [ ]:
True, int(True), False, int(False)

(True, 1, False, 0)

In [ ]:
x > 50

array([ True, False, False,  True,  True,  True, False,  True, False,
       False])

In [ ]:
(x > 50).astype(int).sum()

5

In [ ]:
np.sum(x > 50)

5

In [ ]:
True + True

2

## 도전: 서울시 5월 일자별 평균기온

In [ ]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6,
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9,
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5,
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

"""
평균기온이 25도를 넘는 날수는 총 21일
평균기온이 25를 넘는 날의 평균 기온은 약 26.8도
"""
None

In [ ]:
len(temp[temp > 25])

21

In [ ]:
sum(temp[temp > 25])/len(temp[temp > 25])

26.857142857142858